#!/bin/bash
find ./* -depth -type f -name \*.mkv -o -name \*.avi -o -name \*.mp4 -o -name \*.ogm | parallel -j+0 --gnu --keep-order '(nice -n 19 ffmpeg -i {} -acodec libopus -vn {.}.opus -loglevel quiet)' | zenity --progress --pulsate --auto-close --title "Transcoding Audio" --text="Transcoding with $(nproc) cores..."
