#!/bin/bash
# Variables
compiledir=$HOME/.local/src/encoding/
threads=$(expr $(nproc) + 1)
compile="make -j$threads"
flags='march=native -O3 -pipe -Wall'

# Clean up system
sudo apt-get remove ffmpeg -y
sudo apt-get remove x264 -y
sudo apt-get remove fdk-aac -y
sudo apt-get remove libav -y
sudo apt-get remove libav-git -y
sudo apt-get remove x264-git -y
sudo apt-get remove ffmpeg-git -y
sudo apt-get remove fdk-aac-git -y

# Install dependencies
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install mkvtoolnix autoconf automake build-essential checkinstall git parallel libass-dev libfaac-dev libgpac-dev libmp3lame-dev libopus-dev libsdl1.2-dev libtheora-dev libtool libva-dev libvdpau-dev libvorbis-dev libvpx-dev libx11-dev libxext-dev libxfixes-dev pkg-config texi2html yasm zlib1g-dev libjack-jackd2-dev -y
sudo apt-get build-dep x264 libav -y

## Precise/Saucy dependencies
if [ -n "$(cat /etc/lsb-release | grep precise)" ] || [ -n "$(cat /etc/lsb-release | grep saucy)" ]
   then
      wget http://launchpadlibrarian.net/158788844/libopus-dev_1.1-0ubuntu1_amd64.deb
      sudo dpkg -i libopus-dev*.deb
      rm libopus-dev*
fi

# Make and/or Clean Directory
sudo rm $compiledir -R
mkdir $compiledir -p

# Download Git Repositories
cd $compiledir
git clone git://git.videolan.org/x264.git
git clone https://github.com/FFmpeg/FFmpeg

# Compile x264
cd $compiledir/x264
./configure --enable-static --enable-shared --bit-depth=10
CFLAGS='$flags' $compile
sudo checkinstall -y --pkgname=x264-git --pkgversion="3:$(./version.sh | awk -F'[" "]' '/POINT/{print $4"+git"$5}')"
make distclean

# Compile ffmpeg
cd $compiledir/FFmpeg
./configure --enable-shared --enable-gpl --enable-libfaac --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-x11grab --extra-ldflags=-L/usr/local/lib
CFLAGS='$flags' $compile
sudo checkinstall  -y --pkgname=ffmpeg-git --pkgversion="5:$(date +%Y%m%d%H%M)-git"
hash -r
make distclean

# Recompile x264 with lavf support
cd $compiledir/x264
./configure --enable-static --enable-shared --bit-depth=10
CFLAGS='$flags' $compile
sudo checkinstall -y --pkgname=x264-git --pkgversion="3:$(./version.sh | awk -F'[" "]' '/POINT/{print $4"+git"$5}')"
make distclean

# Add /usr/local/lib to ld
sudo sh -c "echo '/usr/local/lib' > /etc/ld.so.conf.d/encoding-tools.conf"
sudo ldconfig
