#!/bin/bash

if [ "$1" == "" ]
   then
      echo "Enter the CRF Value."
      read crf
   else
      crf="$1"
fi

find ./* -depth -type f -name \*.mkv -o -name \*.avi -o -name \*.mp4 | parallel -j+0 --gnu nice -n 19 x264 --tune animation --level 5.2 --preset placebo --subme 11 --me umh --merange 64 --cabac --weightb --threads 1  --crf $crf --ref 16 --trellis 2 --bframes 16 --b-pyramid normal --deblock 1:1 --aq-mode 2 --aq-strength 1 --psy-rd 0.2:0 --rc-lookahead 100 --output {.}_encoded.mkv {}
